arm7dof:
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
     - joint0
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  